services:
  api:
    networks:
     - infra
    build: ./api
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      PORT: 4001
    ports:
      - "127.0.0.1:4001:4001"
    volumes:
      - "./.env:/app/.env:ro"
      - "./.env.keys:/app/.env.keys:ro"

  web:
    build:
      context: ./web
      args:
        VITE_API_URL: http://localhost
    restart: unless-stopped
    depends_on:
      - api
    ports:
      - "127.0.0.1:4000:4000"

networks:
  infra:
    external: true
